# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bc9cf9b66992f8828ee35fc4a678e18a9ed5e079a6b3a74b88659284a2c1f0b330dca062317c8fec82756a05260d5413a83099c376d7166863d4c9635ec85ab

test:
  secret_key_base: 11744af4d73b08334b2f7ea47587258f82aa3d1f17e2ae5e6c8ee140e9d73e794637b5ed3c256b363d6f4cc017dc844e8424acc247ad5c4b51f2adf04df787ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
